add support for includes and excludes to the oci.vault config
micronaut-projects/micronaut-oracle-cloud pull request #1011
Opened 2024-11-10 15:50 UTC by schangj09

- implement include/exclude filters in OracleCloudVaultConfigurationClient
- make getSecretValue Retryable
- add javadocs

2024-11-10 15:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/micronaut-projects/micronaut-oracle-cloud?pullRequest=1011) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/micronaut-projects/micronaut-oracle-cloud?pullRequest=1011) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/micronaut-projects/micronaut-oracle-cloud?pullRequest=1011) it.</sub>

2024-11-10 18:48 UTC, graemerocher requested changes

2024-11-10 18:48 UTC, graemerocher commented on oraclecloud-vault/src/main/java/io/micronaut/oraclecloud/discovery/vault/OracleCloudVaultConfiguration.java
> +        private String[] excludes = new String[0];
you can use `StringUtils.EMPTY_STRING_ARRAY` to refer to constants for these

2024-11-10 18:48 UTC, graemerocher commented on oraclecloud-vault/src/main/java/io/micronaut/oraclecloud/discovery/vault/OracleCloudVaultConfiguration.java
> +        public String[] getIncludes() {
please add nullability annotations `io.micronaut.core.annotation.NonNull` and `Nullable` to the return types of the methods and arguments

2024-11-10 18:48 UTC, graemerocher commented on oraclecloud-vault/src/main/java/io/micronaut/oraclecloud/discovery/vault/OracleCloudVaultConfigurationClient.java
> +     */
nice javadoc improvement!

2024-11-10 18:48 UTC, graemerocher commented on oraclecloud-vault/src/test/groovy/io/micronaut/oraclecloud/discovery/vault/OracleCloudVaultConfigurationClientNoConfigSpec.groovy
> -@Requires({ System.getenv("VAULT_OCID") && System.getenv("VAULT_SECRETS_COMPARTMENT_OCID") && System.getenv("VAULT_SECRET_NAME") && System.getenv("VAULT_SECRET_VALUE") })
please revert this change otherwise it won't work on CI

2024-11-10 18:49 UTC, graemerocher commented on oraclecloud-vault/src/main/java/io/micronaut/oraclecloud/discovery/vault/OracleCloudVaultConfigurationClient.java
> +        delay = "${oci.vault.config.refresh.retry.delay:1s}"
is the inclusion of `refresh` in the path intentional here?

2024-11-11 10:40 UTC, schangj09 commented on oraclecloud-vault/src/main/java/io/micronaut/oraclecloud/discovery/vault/OracleCloudVaultConfigurationClient.java
> +        delay = "${oci.vault.config.refresh.retry.delay:1s}"
No, it wasn't . I will correct it.

But, it turns out, I tried to test this by introducing an occasional failure. The `@Retryable` seems to not function in the bootstrap context. Do you know if it works in bootstrap?

I think it might be necessary to implement retry directly. Below is what I had in mind. With that implementation my test cases pass.

The question is: Should I include it in this pull request or would you rather that implementation of retry be handled in a separate follow on pull request?

```java
    /**
     * Get the secret bundle with retry because getSecretValue will occasionally fail, and during bootstrap
     * we should not fail. Since we just got the secret id from the listSecrets endpoint, we can
     * presume it is likely a transient failure.
     *
     * @param secretOcid the ocid of the secret to fetch
     * @return the decoded content of the secret bundle
     */
    byte[] getSecretValueWithRetry(String secretOcid) {
        Mono<byte[]> mono = Mono.fromCallable(() -> getSecretValue(secretOcid));

        return mono.retryWhen(
            Retry.fixedDelay(
                oracleCloudVaultClientConfiguration.getRetryAttempts(),
                oracleCloudVaultClientConfiguration.getRetryDelay()
            ).doAfterRetry(signal -> {
                if (LOG.isDebugEnabled()) {
                    LOG.debug("Error occurred while retrieving secret bundle value for {}, will retry", secretOcid, signal.failure());
                }
            })
        ).doOnError(ex -> {
            LOG.error("Failed to retrieve secret {}", secretOcid, ex);
        }).block();
    }
```

2024-11-11 10:40 UTC, schangj09 commented on oraclecloud-vault/src/test/groovy/io/micronaut/oraclecloud/discovery/vault/OracleCloudVaultConfigurationClientNoConfigSpec.groovy
> -@Requires({ System.getenv("VAULT_OCID") && System.getenv("VAULT_SECRETS_COMPARTMENT_OCID") && System.getenv("VAULT_SECRET_NAME") && System.getenv("VAULT_SECRET_VALUE") })
The reason I removed it is because I fixed the @MockBean for secrets() and vaults() in this test.

It turns out that the mocks previously were being ignored due to the missing `@BootstrapContextCompatible`. Once you add that, then it fails due to conflict, and then I added `@Primary ` to make the test pass. It runs locally (without the VAULT_OCID).

2024-11-11 12:50 UTC, graemerocher commented on oraclecloud-vault/src/main/java/io/micronaut/oraclecloud/discovery/vault/OracleCloudVaultConfigurationClient.java
> +        delay = "${oci.vault.config.refresh.retry.delay:1s}"
yes I think it may be necessary to do what you suggested. Bootstrap context is more limited in functionality

2024-11-11 12:51 UTC, graemerocher commented on oraclecloud-vault/src/main/java/io/micronaut/oraclecloud/discovery/vault/OracleCloudVaultConfigurationClient.java
> +        delay = "${oci.vault.config.refresh.retry.delay:1s}"
separately adding configuration options to the `oracleCloudVaultClientConfiguration` will help with IDE completion and documentation so is superior in that way too

2024-11-11 15:23 UTC, schangj09 commented on oraclecloud-vault/src/main/java/io/micronaut/oraclecloud/discovery/vault/OracleCloudVaultConfiguration.java
> +        public String[] getIncludes() {
Added @NonNull for these.

2024-11-11 15:24 UTC, schangj09 commented on oraclecloud-vault/src/main/java/io/micronaut/oraclecloud/discovery/vault/OracleCloudVaultConfigurationClient.java
> +     */
Thanks!

2024-11-11 15:24 UTC, schangj09 commented on oraclecloud-vault/src/main/java/io/micronaut/oraclecloud/discovery/vault/OracleCloudVaultConfiguration.java
> +        private String[] excludes = new String[0];
I updated it

2024-11-11 15:39 UTC, schangj09 commented on oraclecloud-vault/src/main/java/io/micronaut/oraclecloud/discovery/vault/OracleCloudVaultConfigurationClient.java
> +        delay = "${oci.vault.config.refresh.retry.delay:1s}"
ok, I pushed the retry changes with updated test cases

2024-11-11 16:47 UTC, graemerocher approved these changes

2024-11-11 16:51 UTC, graemerocher commented
Created https://github.com/micronaut-projects/micronaut-oracle-cloud/pull/1013 so we can get the whole CI running

2024-11-11 17:09 UTC, merged

2024-11-11 17:09 UTC, graemerocher commented
Thanks for the contribution!