Create OpenAPI Kubernetes client integration with OKE
micronaut-projects/micronaut-oracle-cloud pull request #1041
Opened 2024-12-12 18:06 UTC by andriy-dmytruk

Integration the OpenAPI Kubernetes client with OKE by adding:
- `OkeKubeConfigLoader` that loads kubeconfig from a specified cluster with the OCI Container Engine client.
- `OkeKuberenetesCredentialLoader` that provides token for OKE server requests. The tokens are based on the OCI `AuthenticationDetailsProvider`

2024-12-12 19:45 UTC, graemerocher requested changes

2024-12-12 19:45 UTC, graemerocher commented on oraclecloud-oke-kubernetes-client/src/main/java/io/micronaut/oraclecloud/oke/kubernetes/client/OkeKubeConfigLoader.java
> +public class OkeKubeConfigLoader extends AbstractKubeConfigLoader {
annotated with `@Internal` and declare `final`

2024-12-12 19:45 UTC, graemerocher commented on oraclecloud-oke-kubernetes-client/src/main/java/io/micronaut/oraclecloud/oke/kubernetes/client/OkeKubernetesClientConfig.java
> +        String clusterId,
add `@NotBlank` validation

2024-12-12 19:45 UTC, graemerocher commented on oraclecloud-oke-kubernetes-client/src/main/java/io/micronaut/oraclecloud/oke/kubernetes/client/OkeKubernetesClientConfig.java
> +public record OkeKubernetesClientConfig(
does this need `BootstrapContextCompatible`?

2024-12-13 09:43 UTC, msupic commented on oraclecloud-oke-kubernetes-client/src/main/java/io/micronaut/oraclecloud/oke/kubernetes/client/OkeKubernetesCredentialLoader.java
> +                    base64Encode(builder.toString()),
Not sure if I understand this correctly:
- we don't execute any `oci` command?
- we use the generated URL as a token (which is added to the Authorization Bearer request header)?

2024-12-13 09:57 UTC, n0tl3ss approved these changes

2024-12-13 10:02 UTC, msupic commented on oraclecloud-oke-kubernetes-client/src/main/java/io/micronaut/oraclecloud/oke/kubernetes/client/OkeKubernetesCredentialLoader.java
> +                    ZonedDateTime.now().plusMinutes(4)
Should this expiration be configurable? Is it hardcoded somewhere in oci service to 4 minutes?

2024-12-13 10:05 UTC, msupic commented on oraclecloud-oke-kubernetes-client/src/main/java/io/micronaut/oraclecloud/oke/kubernetes/client/OkeKubernetesCredentialLoader.java
> +final class OkeKubernetesCredentialLoader implements KubernetesTokenLoader {
Should this credential loader replace `io.micronaut.kubernetes.client.openapi.credential.ExecCommandCredentialLoader` or we need both?

2024-12-13 10:33 UTC, msupic commented on oraclecloud-oke-kubernetes-client/src/main/java/io/micronaut/oraclecloud/oke/kubernetes/client/OkeKubernetesCredentialLoader.java
> +                    ZonedDateTime.now().plusMinutes(4)
Is that expiration the same as one that can be set when downloading kube config file?
```
        CreateClusterKubeconfigContentDetails body = CreateClusterKubeconfigContentDetails.builder()
                .tokenVersion(TOKEN_VERSION)
                .endpoint(endpointType)
                .expiration(...)
                .build();
```

2024-12-13 15:22 UTC, andriy-dmytruk commented
Strange, it says region provider is missing. But it should not be required if endpoint was set explicitly. I don't even see RegionProvider injected in the `ContainerEngineClientFactory`.
```
Path Taken: new KubernetesHttpClientFactory(KubeConfigLoader kubeConfigLoader,KubernetesClientConfiguration kubernetesClientConfiguration,KubernetesPrivateKeyLoader kubernetesPrivateKeyLoader,ResourceResolver resourceResolver,DefaultHttpClientFilterResolver defaultHttpClientFilterResolver) --> new KubernetesHttpClientFactory([KubeConfigLoader kubeConfigLoader],KubernetesClientConfiguration kubernetesClientConfiguration,KubernetesPrivateKeyLoader kubernetesPrivateKeyLoader,ResourceResolver resourceResolver,DefaultHttpClientFilterResolver defaultHttpClientFilterResolver) --> new OkeKubeConfigLoader([ContainerEngineClient containerEngineClient],OkeKubernetesClientConfig config,ResourceResolver resourceResolver) --> ContainerEngineClientFactory.build(Builder clientBuilder,AbstractAuthenticationDetailsProvider authenticationDetailsProvider,[RegionProvider regionProvider])
```

2024-12-13 15:25 UTC, andriy-dmytruk commented on oraclecloud-oke-kubernetes-client/src/main/java/io/micronaut/oraclecloud/oke/kubernetes/client/OkeKubernetesCredentialLoader.java
> +                    base64Encode(builder.toString()),
Essentially, yes. The implementation replicates what the oci command would do, which is better, since we can't assume that command is always present. Also oci command initiates a new session every time.

The code is replicated from the python code referenced in method. The token is a URL, but also the signature. Essentially, it contains everything that is needed to verify OCI credentials (the signature is based on `AuthenticationDetailsProvider` signer).

2024-12-13 15:28 UTC, andriy-dmytruk commented on oraclecloud-oke-kubernetes-client/src/main/java/io/micronaut/oraclecloud/oke/kubernetes/client/OkeKubernetesCredentialLoader.java
> +                    ZonedDateTime.now().plusMinutes(4)
The token contains a signature that is based on a date.

As per [OCI Request Signatures](https://docs.oracle.com/en-us/iaas/Content/API/Concepts/signingrequests.htm)
> If the client's clock is skewed more than 5 minutes, a 401 (NotAuthenticated) HTTP status code is returned. This will affect your API requests. For more information, see [Maximum Allowed Client Clock Skew](https://docs.oracle.com/en-us/iaas/Content/API/Concepts/usingapi.htm#clock).

So we can use the token for 5 minutes after its creation (4 with 1 minute buffer)

2024-12-13 15:30 UTC, andriy-dmytruk commented on oraclecloud-oke-kubernetes-client/src/main/java/io/micronaut/oraclecloud/oke/kubernetes/client/OkeKubernetesCredentialLoader.java
> +final class OkeKubernetesCredentialLoader implements KubernetesTokenLoader {
I guess it could. But it only works if the exec command is actually `oci ce clusters generate-token` (which it verifies before making the request).

2024-12-13 15:39 UTC, andriy-dmytruk commented
@n0tl3ss Unfortunately it seems like https://github.com/micronaut-projects/micronaut-oracle-cloud/pull/1040 is breaking this.

2024-12-13 15:48 UTC, n0tl3ss commented on oraclecloud-oke-kubernetes-client/src/test/groovy/io/micronaut/oraclecloud/oke/kubernetes/client/MockKubernetesSpec.groovy
> +            return Region.CA_TORONTO_1
can you try to return null

2024-12-13 16:02 UTC, andriy-dmytruk commented on oraclecloud-oke-kubernetes-client/src/test/groovy/io/micronaut/oraclecloud/oke/kubernetes/client/MockKubernetesSpec.groovy
> +            return Region.CA_TORONTO_1
Yes, thanks

2024-12-13 16:06 UTC, msupic approved these changes

2024-12-13 17:50 UTC, n0tl3ss commented
The sonar reports that volatile isn't enough for thread safe code.

2024-12-13 18:48 UTC, andriy-dmytruk commented
> The sonar reports that volatile isn't enough for thread safe code.

I copied the volatile part from our openapi kubernetes client credential loader implementation. I think it fine, as implementation only uses volatile when getting the token. When it needs to set the token, it uses a `synchronized` block.

2024-12-13 21:20 UTC, graemerocher approved these changes

2024-12-13 21:22 UTC, merged