Update micrometer docs
micronaut-projects/micronaut-oracle-cloud pull request #150
Opened 2021-03-29 13:18 UTC by recursivecodes

Add a few clarifications.

2021-04-06 12:16 UTC, pgressa requested changes

2021-04-06 12:16 UTC, pgressa commented on src/main/docs/guide/micrometer.adoc
> +To begin, first add the standard dependencies for the Micronaut Micromter module per the https://micronaut-projects.github.io/micronaut-micrometer/latest/guide/#_configuration[documentation].
typo, Microm_e_ter

2021-04-13 13:00 UTC, ilopmar approved these changes

2021-04-13 13:09 UTC, graemerocher approved these changes

2021-04-13 14:04 UTC, pgressa approved these changes

2021-04-13 14:04 UTC, merged