ci: version to 3.0.0 Micronaut 4.0.0-SNAPSHOT githubCoreBranch=4.0.x
micronaut-projects/micronaut-oracle-cloud pull request #411
Opened 2022-09-19 17:50 UTC by wetted

2022-09-21 04:50 UTC, sdelamo requested changes

2022-09-21 04:50 UTC, sdelamo commented on .github/workflows/graalvm.yml
> +        graalvm: ['latest', 'dev']
The changes to .graalvm should be in PR against master

2022-09-21 04:50 UTC, sdelamo commented on settings.gradle
> -    versionCatalogs {
can you submit these changes to `master` as well.

2022-09-21 15:39 UTC, wetted commented on settings.gradle
> -    versionCatalogs {
https://github.com/micronaut-projects/micronaut-oracle-cloud/pull/412

2022-11-30 18:42 UTC, wetted commented
I had to make some changes to the following classes, due to changed APIs in core and deprecated API that was removed. The following specifically need to be addressed further. I wasn't entirely sure what to do with them.

`io.micronaut.oraclecloud.function.http.FnServletRequest`
`io.micronaut.oraclecloud.function.http.FnServletResponse.FnResponseHeaders.setConversionService`

2022-12-15 13:31 UTC, merged