Upgrade to Micronaut 4.0.x
micronaut-projects/micronaut-oracle-cloud pull request #453
Opened 2022-12-20 13:18 UTC by alvarosanchez

2022-12-23 17:10 UTC, alvarosanchez commented
@yawkat please move this forward if you can

2023-01-03 09:10 UTC, graemerocher approved these changes

2023-01-03 09:39 UTC, yawkat requested changes

2023-01-03 09:39 UTC, yawkat commented on oraclecloud-function-http/src/main/java/io/micronaut/oraclecloud/function/http/FnMultiValueMap.java
> +        this(map, new DefaultMutableConversionService());
I think this should be

```suggestion
        this(map, ConversionService.SHARED);
```

2023-01-03 09:39 UTC, yawkat commented on oraclecloud-function-http/src/main/java/io/micronaut/oraclecloud/function/http/HttpFunction.java
> +        this.conversionService = new DefaultMutableConversionService();
same here

2023-01-03 09:39 UTC, yawkat commented on buildSrc/src/main/groovy/io.micronaut.build.internal.oraclecloud-module.gradle
> +    api platform("com.oracle.oci.sdk:oci-java-sdk-bom:$oci3Version")
I think it should be possible to just change ociVersion now, and remove the special oci3Version property. We don't need the oci sdk 2 anymore.

2023-01-10 14:16 UTC, alvarosanchez commented
So I was under the impression that we had to move away from `ConversionService.SHARED` for Micronaut 4. I have seen this change in many other modules that upgraded to 4. Is it not the case?

2023-01-16 15:32 UTC, yawkat commented
@alvarosanchez ConversionService.SHARED is deprecated because it does not include all converters. You need to get the conversion service from the app context to get all converters. Calling the constructor does not fix this.

2023-01-17 10:34 UTC, alvarosanchez commented
> You need to get the conversion service from the app context to get all converters. Calling the constructor does not fix this.

I did that in all places where the application context was available (or could be injected).

There is only one place where we can't do this AFAIK, and is the default constructor of `io.micronaut.oraclecloud.function.http.HttpFunction`, since that will be invoked via reflection by `com.fnproject.fn.runtime.EntryPoint`.

One more thing: `ConversionService.SHARED = new DefaultMutableConversionService()`, so reverting to the former is a bit pointless.

2023-01-17 12:53 UTC, yawkat commented
Yea this one can't be replaced by the context conversion service.

@dstepanov what is the right thing to do here? `ConversionService.SHARED` or a new mutable one?

2023-01-17 13:22 UTC, alvarosanchez commented
@graemerocher @yawkat this is potentially ready, please review.

2023-01-17 14:22 UTC, yawkat approved these changes

2023-01-17 14:50 UTC, merged