Use Micronaut serde for the oci java sdk netty client
micronaut-projects/micronaut-oracle-cloud pull request #549
Opened 2023-04-28 01:14 UTC by andriy-dmytruk

# Structure

* The `oraclecloud-httpclient-netty` is modified to serialize with `micronaut-serde`. The object mapper is configured to serialize dates with strings and to use the explicitly set filter.
* The `oraclecloud-serde-processor` can process `java-sdk` sources to create serializable introspections. In particular, it adds `@Nullable` annotation to constructor, ignores the `@Deserialize(builder=)` parameter and changes the target introspection package.
* The `me.champeau.includegit` plugin pulls the oci-java-sdk repository from public github.
* The oci java SDK modules are imported by the `settings-build-logic` module, which:
    - Builds them with gradle adding the `oraclecloud-serde-processor` as annotation processor, then filters out only the the metadata classes (ending with `$Introspected` or `$IntrospectionRef`)
    - Adds the `micronaut-oraclecloud-httpclient-netty` as a dependency to each
    - Transforms the `bmc-` dependencies to the metadata `oraclecloud-bmc-` dependencies (for example, `bmc-objectstorage` depends on `bmc-objectstorage-generated`, so the metadata module `oraclecloud-bmc-objectstorage` will depend on the metadata module `oraclecloud-bmc-objectstorage-generated`).
    - Adds the dependency to the original module (`bmc-objectstorage` for `oraclecloud-bmc-objectstorage`). Since we filter out only the metadata bytecode to the jar, the dependency is required to include the built sources.
 * Tests with some of the created metadata modules are run in the `oraclecloud-httpclient-netty-module`.

2023-05-03 08:13 UTC, graemerocher requested changes

2023-05-03 08:13 UTC, graemerocher commented on buildSrc/src/main/groovy/io.micronaut.build.internal.oraclecloud-base.gradle
> +        mavenLocal()
remove `mavenLocal`

2023-05-03 08:13 UTC, graemerocher commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/serde/MicronautSerdeSerializer.java
> +public class MicronautSerdeSerializer implements Serializer {
make `final`, annotate with `@Internal` and rename to `OciSdkMicronautSerializer`

2023-05-03 08:13 UTC, graemerocher commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/serde/filter/ExplicitlySetPropertyFilter.java
> +public class ExplicitlySetPropertyFilter implements PropertyFilter {
does this need to be public? Annotate it with `@Internal` and make `final`

2023-05-03 08:13 UTC, graemerocher commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/serde/serializers/ErrorCodeAndMessageDeserializer.java
> +public class ErrorCodeAndMessageDeserializer implements Deserializer<ResponseHelper.ErrorCodeAndMessage> {
does this need to be public? Annotate it with `@Internal` and make `final`

2023-05-03 13:18 UTC, yawkat commented on config/checkstyle/checkstyle.xml
> +<!--        <property name="lineSeparator" value="lf"/>-->
is this necessary?

```suggestion
        <property name="lineSeparator" value="lf"/>
```

2023-05-03 13:20 UTC, yawkat commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/NettyHttpProvider.java
> +        return MicronautSerdeSerializer.getDefaultSerializer();
there should be a way to use the mapper from the application context, but can probably do that in another pr.

2023-05-03 13:20 UTC, graemerocher commented
Could you also resolve the conflicts?

2023-05-03 13:21 UTC, yawkat commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/serde/serializers/ErrorCodeAndMessageDeserializer.java
> +                default:
add skipChildren()

2023-05-03 13:21 UTC, yawkat commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/serde/serializers/ErrorCodeAndMessageDeserializer.java
> +                    response.messageArguments(deserializeMap(decoder, context));
add break

2023-05-03 15:16 UTC, andriy-dmytruk commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/serde/serializers/ErrorCodeAndMessageDeserializer.java
> +                default:
What do you mean?

2023-05-03 16:28 UTC, andriy-dmytruk commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/serde/serializers/ErrorCodeAndMessageDeserializer.java
> +                default:
Added `decoder.skipValue()`

2023-05-16 06:35 UTC, yawkat approved these changes

2023-05-17 08:58 UTC, graemerocher approved these changes

2023-05-17 12:14 UTC, yawkat commented on oraclecloud-httpclient-netty/build.gradle
> +    //it.systemProperty("test.compartment.id", "ocid1.compartment.oc1..aaaaaaaaqpsmu5vcjf75ejqwvhhg75ndjpjdmxihi2gltvb5zazhv2oe7wea")
remove this, i added this for local testing.

can we run these tests on CI somehow @graemerocher?

2023-05-17 12:15 UTC, yawkat commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/serde/OciSdkMicronautSerializer.java
> +    private static final Map<String, Object> DEFAULT_MAPPER_CONFIG = new HashMap<String, Object>() {{
avoid this syntax, it creates an anonymous class and increases jar size

2023-05-17 12:16 UTC, yawkat commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/serde/OciSdkMicronautSerializer.java
> +    private static final Map<String, Object> DEFAULT_MAPPER_CONFIG = new HashMap<String, Object>() {{
can just use Map.of now. or maybe even remove this config entirely, since writeDatesAsTimestamps is obsolete.

2023-05-17 12:17 UTC, yawkat commented on oraclecloud-httpclient-netty/build.gradle
> +    //it.systemProperty("test.compartment.id", "ocid1.compartment.oc1..aaaaaaaaqpsmu5vcjf75ejqwvhhg75ndjpjdmxihi2gltvb5zazhv2oe7wea")
```suggestion
```

2023-05-17 14:26 UTC, andriy-dmytruk commented on buildSrc/src/main/groovy/io.micronaut.build.internal.oraclecloud-bom.gradle
> +    // TODO make sure that both versions match and use only artifacts of one
We probably want to throw an error or warning here if there is a mismatch in versions. Altogether could be:
```java
    String ociVersion = libs.oci.bom.get().version
    String ociProjectVersion = new XmlSlurper().parse("checkouts/oci-java-sdk/bmc-bom/pom.xml").version.text()
    def ociProjectArtifacts = parseOciBomArtifacts(repositories.mavenCentral(), ociProjectVersion)
    
    if (ociVersion != ociProjectVersion) {
        throw new GradleException(
                "The version of checked out from github repository oci java sdk (${ociProjectVersion})" +
                " must match the one in the bom (${ociVersion})")
    }
    
    extraPropertiesExtension.set('ociArtifacts', ociProjectArtifacts)
    extraPropertiesExtension.set('ociVersion', ociVersion)
 ```
 
 I could not do this before, as I didn't have the right version in the oci SDK github repository.
 
 Also, the `parseOciBomArtifacts` method no longer needs the first parameter now.

2023-05-17 17:40 UTC, merged