Use micronaut-http-client connection pooling
micronaut-projects/micronaut-oracle-cloud pull request #576
Opened 2023-05-19 13:58 UTC by yawkat

This PR implements connection pooling using the existing pooling infrastructure from micronaut-http-client. There are now two providers, the old SPI NettyHttpProvider and the new ManagedNettyHttpProvider, which is managed by the ApplicationContext so that it can reuse the same DefaultHttpClient (which the user can also configure using micronaut config). AbstractSdkClientFactory requests the managed provider and injects it into managed clients.

OCI SDK config on the managed client (timeouts, SSL settings and such) does not work anymore. It should instead be configured using the `micronaut.http.services.oci` config key, like a normal http client.

The managed client still uses the same (unmanaged) OciSdkMicronautSerializer. I think it should switch to a managed serializer in the future, and I've added a todo comment for this. However it will require some more changes (jackson-databind compatibility) so I didn't do it in this PR.

2023-05-19 14:04 UTC, graemerocher requested changes

2023-05-19 14:04 UTC, graemerocher commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/ManagedNettyHttpProvider.java
> +class ManagedNettyHttpProvider implements HttpProvider {
does this not need to require the present of the `oci` http client configuration?

2023-05-19 14:20 UTC, yawkat commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/ManagedNettyHttpProvider.java
> +class ManagedNettyHttpProvider implements HttpProvider {
It can't be final, it's extended by a test to make sure that this provider is used.

The client config for oci is not needed, it works fine with the default config.

2023-05-19 14:39 UTC, graemerocher approved these changes

2023-05-19 14:50 UTC, merged

2023-05-19 15:03 UTC, andriy-dmytruk commented on oraclecloud-httpclient-netty/build.gradle
> +    implementation mn.micronaut.http.client
Probably the dependency could be optional or compileOnly, so it is not included when micronaut context is not present (SDK is not used in a micronaut application).

2023-05-22 06:15 UTC, yawkat commented on oraclecloud-httpclient-netty/build.gradle
> +    implementation mn.micronaut.http.client
it's still required in that case, when no context is available I just construct a contextless DefaultHttpClient