[DRAFT] Initial implementation of integration with Oracle Cloud Certificates
micronaut-projects/micronaut-oracle-cloud pull request #596
Opened 2023-05-31 15:46 UTC by n0tl3ss

- TBA

2023-06-01 07:23 UTC, yawkat commented on oraclecloud-certificates/src/main/java/io/micronaut/oraclecloud/certificates/ssl/DelegatedSslContext.java
> +public class DelegatedSslContext extends SslContext {
internal

2023-06-01 15:27 UTC, graemerocher requested changes

2023-06-01 15:27 UTC, graemerocher commented on oraclecloud-certificates/src/main/java/io/micronaut/oraclecloud/certificates/events/CertificateEvent.java
> +public record CertificateEvent(PrivateKey privateKey, X509Certificate certificate) {
add nullable annotations, validate parameters if null not allowed

2023-06-01 15:27 UTC, graemerocher commented on oraclecloud-certificates/src/main/java/io/micronaut/oraclecloud/certificates/ssl/DelegatedSslContext.java
> +public class DelegatedSslContext extends SslContext {
make `final`

2023-06-05 16:33 UTC, n0tl3ss commented on oraclecloud-certificates/src/main/java/io/micronaut/oraclecloud/certificates/events/CertificateEvent.java
> +public record CertificateEvent(PrivateKey privateKey, X509Certificate certificate) {
I added on both parameters `@NonNull`, is that enough?

2023-06-05 16:34 UTC, n0tl3ss commented on oraclecloud-certificates/src/main/java/io/micronaut/oraclecloud/certificates/background/OracleCloudCertificationRefresherTask.java
> +        oracleCloudCertificateService.refreshCertificate();
I surrounded call with catch generic Exception, maybe it could be more specific WDYT @graemerocher?

2023-06-05 19:57 UTC, graemerocher approved these changes

2023-06-06 10:01 UTC, merged