Use managed HttpProvider for MonitoringIngestionClient
micronaut-projects/micronaut-oracle-cloud pull request #839
Opened 2024-03-05 14:05 UTC by yawkat

this prevented adding logging properties

2024-03-05 14:07 UTC, graemerocher requested changes

2024-03-05 14:07 UTC, graemerocher commented on oraclecloud-micrometer/src/main/java/io/micronaut/oraclecloud/monitoring/MonitoringIngestionClient.java
> +    void setHttpProvider(@Nullable HttpProvider httpProvider) {
please move this to a constructor argument and deprecate the previous constructor

2024-03-05 14:09 UTC, yawkat commented on oraclecloud-micrometer/src/main/java/io/micronaut/oraclecloud/monitoring/MonitoringIngestionClient.java
> +    void setHttpProvider(@Nullable HttpProvider httpProvider) {
ok done

2024-03-05 14:13 UTC, n0tl3ss approved these changes

2024-03-06 08:14 UTC, graemerocher approved these changes

2024-03-06 08:15 UTC, merged