add support for filters inside the oci netty client
micronaut-projects/micronaut-oracle-cloud pull request #954
Opened 2024-07-23 14:16 UTC by n0tl3ss

PR:

- adds support for filters inside netty client 
- for metrics adds a filter that measures time for each request
- metrics filter also support ignoring path 

![metrics-explorer](https://github.com/user-attachments/assets/4b06aa77-bb6f-452c-b6b9-fc206892c7c2)

Pr bumps `micronaut-micrometer` to `5.7.1` so it should probably target `4.3.x` branch which currently doesn't exists.

2024-07-23 14:33 UTC, graemerocher commented
4.2.x hasn't been released yet so the target is fine

2024-07-23 14:47 UTC, graemerocher requested changes

2024-07-23 14:47 UTC, graemerocher commented on oraclecloud-micrometer/src/main/java/io/micronaut/oraclecloud/monitoring/sdk/SdkMetricsNettyClientFilter.java
> +        tags.add(uri(response, request.uri().getPath()));
I don't think we can include the path here, it has to be the path template. This could lead to the metrics explosion issue

2024-07-23 14:47 UTC, graemerocher commented on oraclecloud-micrometer/src/main/java/io/micronaut/oraclecloud/monitoring/sdk/SdkMetricsNettyClientFilter.java
> +        tags.add(serviceId("oci"));
is there a way to get the OCI service being called for this ? Like object storage etc.

2024-07-23 14:47 UTC, graemerocher commented on oraclecloud-micrometer/src/main/java/io/micronaut/oraclecloud/monitoring/sdk/SdkMetricsNettyClientFilter.java
> +        List<Tag> tags = new ArrayList<>();
supply a size of 4 to this array

2024-07-23 14:47 UTC, graemerocher commented on oraclecloud-micrometer/src/main/java/io/micronaut/oraclecloud/monitoring/sdk/SdkMetricsNettyClientFilterConfig.java
> + * @param ignorePaths list of url paths that will be skipped for metrics measurement.
should this be a path pattern?

2024-07-23 14:47 UTC, graemerocher commented on oraclecloud-micrometer/src/main/java/io/micronaut/oraclecloud/monitoring/sdk/SdkMetricsNettyClientFilterConfig.java
> +@ConfigurationProperties("micronaut.metrics.oci.sdk.client")
extract the prefix into a constant

2024-07-23 14:47 UTC, graemerocher commented on oraclecloud-oke-workload-identity/src/main/java/io/micronaut/oraclecloud/oke/workload/identity/OkeWorkloadIdentityConfiguration.java
> +                                            @Nullable List<NettyClientFilter> nettyClientFilters) {
retain the original constructor and create a new one annotated with `@Inject` to avoid the breaking API change

2024-07-23 14:47 UTC, graemerocher commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/NettyClientFilter.java
> +public interface NettyClientFilter {
add javadoc, `@since` and nullability annotations. Also rename to `OciNettyClientFilter`

2024-07-23 14:47 UTC, graemerocher commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/NettyClientFilter.java
> +   int getPriority();
make this a default method that returns 0

2024-07-23 14:47 UTC, graemerocher commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/NettyClientFilter.java
> +   int getPriority();
can we not use `OrderUtil` for this and hence support the `@Ordered` annotation?

2024-07-23 14:55 UTC, yawkat commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/NettyClientFilter.java
> +public interface NettyClientFilter {
javadoc

2024-07-23 14:55 UTC, yawkat commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/NettyHttpClientBuilder.java
> +    public HttpClientBuilder registerNettyClientFilterInterceptor(NettyClientFilter nettyClientFilter) {
Is this API necessary? If so, try to make it a NettyClientProperty instead of adding a new method

2024-07-23 14:55 UTC, yawkat commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/NettyHttpRequest.java
> +            filter.beforeRequest(this, context);
how about instead of the context map, you let beforeRequest return an Object that is then passed to afterResponse

2024-07-23 14:55 UTC, yawkat commented on oraclecloud-micrometer/build.gradle
> +    implementation mn.micronaut.http.client
can we make this an optional dependency? compileOnly

2024-07-23 14:55 UTC, yawkat commented on oraclecloud-micrometer/build.gradle
> +    implementation mn.micronaut.http.client
hm I think we can't.

2024-07-23 14:55 UTC, yawkat commented on oraclecloud-micrometer/src/main/java/io/micronaut/oraclecloud/monitoring/sdk/SdkMetricsNettyClientFilter.java
> + * The SdkMetricsNettyClientFilter will emit oci sdk client metrics.
`@since`, `@author`. for other classes too please

2024-07-24 07:20 UTC, yawkat commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/NettyHttpClientBuilder.java
> +    public static final ClientProperty<List<OciNettyClientFilter>> OCI_NETTY_FILTERS_KEY = ClientProperty.create("oci_netty_filters");
Move to NettyClientProperties, add docs, change name to ociNettyFilters to match the serviceId property

2024-07-24 07:21 UTC, yawkat commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/NettyHttpClientBuilder.java
> +//    public HttpClientBuilder registerNettyClientFilterInterceptor(OciNettyClientFilter nettyClientFilter) {
remove fully

2024-07-24 07:21 UTC, yawkat commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/NettyHttpRequest.java
> +            last = last.handle((response, error) -> filter.afterResponse(this, response, error, filter.beforeRequest(this)));
beforeRequest needs to happen before the handle

2024-07-24 07:22 UTC, yawkat commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/OciNettyClientFilter.java
> +   Map<String, Object> beforeRequest(HttpRequest request);
You can change the return value from `Map<String, Object>` to just `Object`. For most filters (including the metrics filter), a full Map isnt necessary.

2024-07-24 07:24 UTC, yawkat commented on oraclecloud-micrometer/src/test/groovy/io/micronaut/oraclecloud/monitoring/sdk/OracleCloudSdkMetricsFilterTest.groovy
> +    def "test oci sdk metrics client filter request returns 4042" () {
```suggestion
    def "test oci sdk metrics client filter request returns 404" () {
```

2024-07-24 08:10 UTC, n0tl3ss commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/NettyHttpRequest.java
> +            last = last.handle((response, error) -> filter.afterResponse(this, response, error, filter.beforeRequest(this)));
good catch :)

2024-07-24 09:02 UTC, yawkat commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/NettyHttpRequest.java
> +            Object beforeRequestResult = filter.beforeRequest(this);
You can make this type safe by introducing a method like this:

```java
private static <T> CompletableFuture<HttpResponse> runFilter(OciNettyClientFilter<T> filter, CompletableFuture<HttpResponse> responseFuture) {
  T beforeRequestResult = filter.beforeRequest(this);
  return responseFuture.handle((response, error) -> filter.afterResponse(this, response, error, beforeRequestResult));
}
```

Then you can avoid the raw type.

2024-07-24 09:02 UTC, yawkat approved these changes

2024-07-24 12:16 UTC, graemerocher requested changes

2024-07-24 12:16 UTC, graemerocher commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/OciNettyClientFilter.java
> +   R beforeRequest(HttpRequest request);
add javadoc and nullability annotations to all methods and return types

2024-07-24 12:16 UTC, graemerocher commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/OciNettyClientFilter.java
> +public interface OciNettyClientFilter<R> extends Ordered {
add `@Indexed(OciNettyClientFilter.class)` to this interface

2024-07-24 12:16 UTC, graemerocher commented on src/main/docs/guide/micrometer.adoc
> +If you are using OCI SDK clients instrumented by Micronaut framework by default for each request metrics will be collected.
document how to ignore paths

2024-07-24 12:18 UTC, n0tl3ss commented on src/main/docs/guide/micrometer.adoc
> +If you are using OCI SDK clients instrumented by Micronaut framework by default for each request metrics will be collected.
There are no more paths

2024-07-24 15:15 UTC, n0tl3ss commented
Probably I will have to join the class and method name. WDYT @graemerocher?
<img width="1032" alt="Screenshot 2024-07-24 at 17 14 14" src="https://github.com/user-attachments/assets/963523f7-9db4-4efe-8544-ab5b9cd2e79e">
<img width="1053" alt="Screenshot 2024-07-24 at 17 13 55" src="https://github.com/user-attachments/assets/91794fed-0b7c-4af3-8f6b-7488d89fad2f">

2024-07-24 17:11 UTC, graemerocher approved these changes

2024-07-24 17:12 UTC, graemerocher commented
yeah maybe one entry combining class name and method name is enough. Also we can probably safely use class simply name and skip the package name

2024-07-24 17:53 UTC, n0tl3ss commented
<img width="1041" alt="image" src="https://github.com/user-attachments/assets/ccb18136-41ea-41ce-b0fe-5a0912d8fc02">
latest changes

2024-07-25 08:16 UTC, yawkat commented
Anything else you want to change? Otherwise you can merge.

2024-07-25 08:19 UTC, merged