Implement netty client using the new micronaut-core RawHttpClient
micronaut-projects/micronaut-oracle-cloud pull request #989
Opened 2024-10-09 09:32 UTC by yawkat

This PR replaces most of the netty-based HTTP client that previously used the low-level micronaut-http-client ConnectionManager API with an implementation based on the new micronaut-http-client-core RawHttpClient introduced in micronaut-core 4.7.0. This offers some advantages:

- Much simpler implementation. Once the legacy implementation is not needed anymore, all classes deprecated in this PR can be removed.
- Possibility to work with non-netty RawHttpClient implementations, once those exist. In particular, this will allow using the JDK http client instead.
- RawHttpClient runs normal micronaut-core ClientFilters, so we won't need the `OciNettyClientFilter` API anymore.

While in theory the new implementation should be a drop-in replacement, it is possible that RawHttpClient differs slightly in behavior. For that reason, I've kept the old implementation around. It can be enabled by the `oci.netty.legacy-netty-client` config property, or the `io.micronaut.oraclecloud.httpclient.netty.legacy-netty-client` system property.

This also means that MicronautHttpRequest and MicronautHttpResponse are actually mostly copied from NettyHttpRequest and NettyHttpResponse. Please consider that when reviewing, the actual changes are not that big.

This PR works and is ready for review, but still needs a release of micronaut-core 4.7.0 (and of micronaut-serialization due to the unrelated https://github.com/micronaut-projects/micronaut-serialization/pull/943 ).

2024-10-09 13:08 UTC, graemerocher requested changes

2024-10-09 13:08 UTC, graemerocher commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/DecidedBodyHandler.java
> +@Deprecated
use `forRemove=true` on all `@Deprecated` types

2024-10-09 13:08 UTC, graemerocher commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/LimitedBufferingSubscriber.java
> +final class LimitedBufferingSubscriber implements Subscriber<ByteBuffer<?>>, Closeable {
add `@Internal`

2024-10-09 13:08 UTC, graemerocher commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/MicronautHeaderMap.java
> +final class MicronautHeaderMap extends AbstractMap<String, List<String>> {
add `@Internal`

2024-10-09 13:08 UTC, graemerocher commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/MicronautHeaderMap.java
> +        return key instanceof String && headers.contains((String) key);
could probably do `instanceof CharSequence` and then `toString()`

2024-10-09 13:08 UTC, graemerocher commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/MicronautHeaderMap.java
> +    private class KeySet extends AbstractSet<String> {
declare `final`

2024-10-09 13:08 UTC, graemerocher commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/MicronautHeaderMap.java
> +    private static class HeaderIterator implements Iterator<Entry<String, List<String>>> {
declare `final`

2024-10-09 13:08 UTC, graemerocher commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/MicronautHttpRequest.java
> +final class MicronautHttpRequest implements HttpRequest {
annotate `@Internal`

2024-10-09 13:26 UTC, yawkat commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/MicronautHeaderMap.java
> +        return key instanceof String && headers.contains((String) key);
the java-sdk client API only allows String so there's no point.

2024-10-09 13:29 UTC, yawkat commented on oraclecloud-httpclient-netty/src/main/java/io/micronaut/oraclecloud/httpclient/netty/DecidedBodyHandler.java
> +@Deprecated
I tried but it marks all uses of the type as an error in IDEA which is a bit confusing. And they're all package-private types anyway so it doesn't matter.

2024-10-17 07:13 UTC, graemerocher approved these changes

2024-11-08 13:33 UTC, merged